-- showing all genres movie count
SELECT
    TV_GENRES.NAME                 AS GENRE,
    COUNT(TV_SHOW_GENRES.GENRE_ID) AS NUMBER_OF_SHOWS
FROM
    TV_GENRES
    INNER JOIN TV_SHOW_GENRES
    ON TV_GENRES.ID = TV_SHOW_GENRES.GENRE_ID
GROUP BY
    TV_SHOW_GENRES.GENRE_ID
ORDER BY
    NUMBER_OF_SHOWS DESC;