-- get show genres
SELECT
    TV_GENRES.NAME
FROM
    TV_GENRES
    JOIN TV_SHOW_GENRES
    ON TV_GENRES.ID = TV_SHOW_GENRES.GENRE_ID JOIN TV_SHOWS
    ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
WHERE
    TV_SHOWS.TITLE = 'Dexter'
ORDER BY
    TV_GENRES.NAME;